-
  name: Test connectivity to target servers
  hosts: aws
  tasks:
    - name: Display resolv.conf contents
      command: cat resolv.conf
      register: resolvout
      args:
              chdir: /etc
    - debug:
            var: resolvout.stdout_lines

    - name: Display date
      command: date
      register: date

    - debug:
            var: date.stdout_lines

    - name: Display uptime
      command: uptime
      register: uptime

    - debug:
            var: uptime.stdout_lines
